### ISSUE TITLE
v28/values-v28.xml not found

### ISSUE THREAD

**Issue by jingchangfa** [searchy2/CustomAlertViewDialogue#10]
compileSdkVersion 27 

error: resource android:attr/fontVariationSettings not found.
error: resource android:attr/dialogCornerRadius not found.
error: resource android:attr/ttcIndex not found.

Message{kind=ERROR, text=error: resource android:attr/dialogCornerRadius not found., sources=[/Users/jing/.gradle/caches/transforms-1/files-1.1/appcompat-1.0.0-rc01.aar/301e547d656966806ea0fc1ade335436/res/values-v28/values-v28.xml:9:5-12:13], original message=, tool name=Optional.of(AAPT)}

**Comment by searchy2** [comment]
What Android Studio version are you on? This library uses Android X so it works best with Android Studio 3.2.0.

**Comment by searchy2** [comment]
Were you able to solve this issue?

**Comment by 917960559** [comment]
I solved it. Just set your compileSdkVersion: 28

**Comment by searchy2** [comment]
Thanks for solving this issue!
