### ISSUE TITLE
v2.6.0 error

### ISSUE THREAD

**Issue by wuxiaolong928** [searchy2/CustomAlertViewDialogue#12]
Error:
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:18:5-116:19 to override.

My Manifest,xml
 <application
        android:name=".KeralaInfoApplication"
        android:allowBackup="false"
        android:hardwareAccelerated="true"
        android:largeHeap="true"
        android:icon="@drawable/appicon"
        android:label="@string/app_name"
        android:roundIcon="@drawable/appicon"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true"
        tools:replace="android:usesCleartextTraffic">

**Comment by searchy2** [comment]
Please add `tools:replace="android:appComponentFactory"` to your application tag to remove the error.
