### ISSUE TITLE
setDecorView(android.view.View)

### ISSUE THREAD

**Issue by robertelo** [searchy2/CustomAlertViewDialogue#4]
Thank you for this awsome work. I had an issue with Cannot resolve method 'setDecorView(android.view.View)' in submit feedback style. 
I use activities. 
               `.setBoxInputHint(boxHint)
                .setBoxInputText(boxText)
                .setDecorView(getWindow().getDecorView())
                .build();`
I commented 
.setDecorView(getWindow().getDecorView())

and the dialog color is becoming radial transparent, it doesn't look like your screenshots.
Please help

**Comment by searchy2** [comment]
The default background without setting setDecorView is a radial transparency. 
Can you tell me what device you are using where setDecorView doesn't work? I've tested the BlurView on all dialogue types and it works for all of them.

**Comment by robertelo** [comment]
Tested in 3 genymotion emulators for example S5. 4.4.4 It's giving me that radial transparency because I commented .setDecorView(getWindow().getDecorView())
I commented it because I had this error in java:  `Cannot resolve method 'setDecorView(android.view.View)'`
Could you 
`  private void showCustomDialog(){
        CustomAlertDialogue.Builder alert;
        alert = new CustomAlertDialogue.Builder(FinalActivity.this)
                .setStyle(CustomAlertDialogue.Style.INPUT)
                .setTitle("Contact us")
                .setTitleColor(R.color.color_yellow)
                .setPositiveText("Submit")
                .setPositiveColor(R.color.positive)
                .setPositiveTypeface(Typeface.DEFAULT_BOLD)
                .setOnInputClicked(new CustomAlertDialogue.OnInputClicked() {
                    @Override
                    public void OnClick(View view, Dialog dialog, ArrayList<String> inputList) {
                        Toast.makeText(FinalActivity.this, "Thank you", Toast.LENGTH_SHORT).show();
                        for (String input : inputList)
                        {
                            Log.d("Input", input);
                        }
                        dialog.dismiss();
                    }
                })

                .setNegativeText("Cancel")
                .setNegativeColor(R.color.negative)
                .setOnNegativeClicked(new CustomAlertDialogue.OnNegativeClicked() {
                    @Override
                    public void OnClick(View view, Dialog dialog) {
                        dialog.dismiss();
                    }
                })
                .setLineInputHint(lineHint)
                .setLineInputText(lineText)
                .setBoxInputHint(boxHint)
                .setBoxInputText(boxText)
                //.setDecorView(getWindow().getDecorView())
                .build();
        alert.show();
    }`

**Comment by robertelo** [comment]
I always get this error in all the activities 
`Cannot resolve method 'setDecorView(android.view.View)'`

**Comment by searchy2** [comment]
The radial transparency appears on 4.4 devices because old Android versions don't support gradients well. I don't know why the setDecorView method cannot be resolved. Can you please post the stack trace?

**Comment by searchy2** [comment]
Nice, are you using the latest version - v2.3.1
The setDecorView was just added recently.

**Comment by searchy2** [comment]
Ah, that's the problem then. Update to the latest version v2.3.1
You're too far behind!
