### ISSUE TITLE
statusbar hide when show dialog.

### ISSUE THREAD

**Issue by xsjqqq123** [searchy2/CustomAlertViewDialogue#5]
can I cancel it ?

**Comment by searchy2** [comment]
Yes, just override the library's styles.

**Comment by TMNMT** [comment]
Hi searchy i'd like to thank you for this nice work,
my problem is:
some time when the Simple alert and Confirmation alert dialog start, their backgrounds takes the bottom of the screen as background for short time, like you can see it in the picture
![screenshot_20180424-001127](https://user-images.githubusercontent.com/34405289/39158117-21868cf8-4756-11e8-8d1a-2030b725ce97.png)

**Comment by searchy2** [comment]
I use fullscreen activities in all my apps so that's why it's the way it is. Overriding the style isn't difficult and I can add it to the documentation in the future. Hope this helps!

**Comment by xsjqqq123** [comment]
I find that can not show new dialog when click actionsheet item,

**Comment by xsjqqq123** [comment]
![image](https://user-images.githubusercontent.com/8264121/39231843-019d1472-489e-11e8-9dbc-45747c79ae32.png)
create new dialog after prefer dismiss also not work.

**Comment by xsjqqq123** [comment]
finally, I solve it..:
![image](https://user-images.githubusercontent.com/8264121/39232730-d17f860a-48a0-11e8-8667-adc1cc0b3a79.png)
