### ISSUE TITLE
Default transition style

### ISSUE THREAD

**Issue by yargeel** [searchy2/CustomAlertViewDialogue#8]
Hello again, and thank you again for nice work!
Is it possible to change default transition style ("slide in from bottom to top")?

**Comment by searchy2** [comment]
Thank you for using this library!

What device are you testing on? The default transition style for Dialogues is fade_in and fade_out.
For Bottom Sheets, it's slide_in_bottom and slide_out_bottom

**Comment by searchy2** [comment]
I believe it is possible to override those transitions by providing your own animations named the same as the resources in the library.

**Comment by yargeel** [comment]
I've tested on emulator (Oreo), ZTE A510 (Android 6), Samsung Galaxy Tab S2 (Android 7).

I tried to extend class CustomAlertDialogue and override init methods, tried to set window\activity animations on theme style, but have no success.

I'll try to override transitions by the same names, hope it helps.

**Comment by searchy2** [comment]
Closing this issue. Please reopen if you have any additional questions.
