### ISSUE TITLE
Not working with the latest dependency

### ISSUE THREAD

**Issue by edwardaksh** [searchy2/CustomAlertViewDialogue#9]
The version of this project is somehow not working with the latest android support library. 
It's throwing multiple merger errors. 
Can you please have a look by creating a new project.
BTW, great work...

**Comment by searchy2** [comment]
Thanks for using this library Edward! 

I updated the dependencies to AndroidX which seems to not work with non Android X projects. If you update your project to Android X, this library should work correctly. 

Android X is fantastic BTW!
